version: '3'
services:
  web:
    image: bskim45/s3-url-shortener:latest
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command:
      - python
      - /app/run.py
    environment:
      - FLASK_DEBUG=1
      - PORT=5000
      - AWS_ACCESS_KEY_ID=__ACCESS_KEY__
      - AWS_SECRET_ACCESS_KEY=__SECRET__
      - S3_REGION=us-west-2
      - S3_BUCKET=__S3_BUCKET__
      - SHORT_DOMAIN=__SHORT_DOMAIN__
