apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3-url-shortener.fullname" . }}-config
  labels:
{{ include "s3-url-shortener.labels" . | indent 4 }}
data:
  S3_BUCKET: "{{ .Values.config.awsS3Bucket }}"
  S3_REGION: "{{ .Values.config.awsS3Region }}"
  PORT: "{{ .Values.config.port }}"
  SHORT_DOMAIN: "{{ .Values.config.shortDomain }}"
