{{- if .Values.extraEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-url-shortener.fullname" . }}-env
  labels:
{{ include "s3-url-shortener.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
