{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "s3-url-shortener.serviceAccountName" . }}
  labels:
{{ include "s3-url-shortener.labels" . | indent 4 }}
{{- end -}}
